name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "23.0"
          elixir-version: "1.10"

      - name: Install dependencies
        run: mix deps.get

      - name: Run "mix format"
        run: mix format --check-formatted --check-equivalent

      - name: Run "mix compile"
        run: mix compile --warnings-as-errors

      - name: Run "mix test"
        run: mix test
